version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              TAG="latest"
            else
              TAG="$CIRCLE_BRANCH"
            fi
            docker build -t gabrielcompan/joke-generator:$TAG .
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 5000:5000 --name docker-joke-container gabrielcompan/joke-generator:$CIRCLE_SHA1
            sleep 5
            wget http://127.0.0.1:5000/
            docker stop docker-joke-container
            docker rm docker-joke-container
      - run:
          name: Push Docker image to DockerHub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push gabrielcompan/joke-generator:$TAG